name: Cloudflare Pages

on:
  push:
  workflow_dispatch: {}
  schedule:
    - cron: "0 15 * * *" # 日本時間の0時に実行


jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      CLOUDFLARE_ACCESS_KEY_ID: ${{secrets.CLOUDFLARE_ACCESS_KEY_ID}}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{secrets.CLOUDFLARE_SECRET_ACCESS_KEY}}
      NOTION_API_KEY: ${{secrets.NOTION_API_KEY}}
      NOTION_MOTTAI_NIGHT_LINK_PAGE_ID: ${{secrets.NOTION_MOTTAI_NIGHT_LINK_PAGE_ID}}
      NOTION_EXPERIENCE_PROGRAM_LINK_PAGE_ID: ${{secrets.NOTION_EXPERIENCE_PROGRAM_LINK_PAGE_ID}}
      NOTION_NEWS_PAGE_ID: ${{secrets.NOTION_NEWS_PAGE_ID}}
      R2_IMAGE_WORKER_URL: ${{secrets.R2_IMAGE_WORKER_URL}}
      R2_URL: ${{secrets.R2_URL}}
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 20.x
      # base: https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      - name: Reconfigure git to use HTTPS authentication for npm-dependencies using Git
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - run: npm ci
      - run: npm run build

      - name: Publish to Cloudflare Pages
        id: cloudflare_pages_deploy
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: mottai-hp-next-chakra
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Add publish URL as commit status
        uses: actions/github-script@v6
        with:
          script: |
            // When "pull_request", context.payload.pull_request?.head.sha is expected SHA.
            // (base: https://github.community/t/github-sha-isnt-the-value-expected/17903/2)
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: 'Cloudflare Pages',
              description: 'Cloudflare Pages deployment',
              state: 'success',
              sha,
              target_url: "${{ steps.cloudflare_pages_deploy.outputs.url }}",
            });
